apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: apache
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: my-deployment
        image: dhanushamk/april-prt
        ports:
        - containerPort: 80
